/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/client/list-restaurants`; params?: Router.UnknownInputParams; } | { pathname: `/client/make-reservation`; params?: Router.UnknownInputParams; } | { pathname: `/client/my-reservations`; params?: Router.UnknownInputParams; } | { pathname: `/client/restaurant-details`; params?: Router.UnknownInputParams; } | { pathname: `/common/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/common/home`; params?: Router.UnknownInputParams; } | { pathname: `/common/profile`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/add-table`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/edit-restaurant`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/edit-table`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/manage-tables`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/register-restaurant`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/client/list-restaurants`; params?: Router.UnknownOutputParams; } | { pathname: `/client/make-reservation`; params?: Router.UnknownOutputParams; } | { pathname: `/client/my-reservations`; params?: Router.UnknownOutputParams; } | { pathname: `/client/restaurant-details`; params?: Router.UnknownOutputParams; } | { pathname: `/common/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/common/home`; params?: Router.UnknownOutputParams; } | { pathname: `/common/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/restaurant/add-table`; params?: Router.UnknownOutputParams; } | { pathname: `/restaurant/edit-restaurant`; params?: Router.UnknownOutputParams; } | { pathname: `/restaurant/edit-table`; params?: Router.UnknownOutputParams; } | { pathname: `/restaurant/manage-tables`; params?: Router.UnknownOutputParams; } | { pathname: `/restaurant/register-restaurant`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/client/list-restaurants${`?${string}` | `#${string}` | ''}` | `/client/make-reservation${`?${string}` | `#${string}` | ''}` | `/client/my-reservations${`?${string}` | `#${string}` | ''}` | `/client/restaurant-details${`?${string}` | `#${string}` | ''}` | `/common/edit-profile${`?${string}` | `#${string}` | ''}` | `/common/home${`?${string}` | `#${string}` | ''}` | `/common/profile${`?${string}` | `#${string}` | ''}` | `/restaurant/add-table${`?${string}` | `#${string}` | ''}` | `/restaurant/edit-restaurant${`?${string}` | `#${string}` | ''}` | `/restaurant/edit-table${`?${string}` | `#${string}` | ''}` | `/restaurant/manage-tables${`?${string}` | `#${string}` | ''}` | `/restaurant/register-restaurant${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/client/list-restaurants`; params?: Router.UnknownInputParams; } | { pathname: `/client/make-reservation`; params?: Router.UnknownInputParams; } | { pathname: `/client/my-reservations`; params?: Router.UnknownInputParams; } | { pathname: `/client/restaurant-details`; params?: Router.UnknownInputParams; } | { pathname: `/common/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/common/home`; params?: Router.UnknownInputParams; } | { pathname: `/common/profile`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/add-table`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/edit-restaurant`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/edit-table`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/manage-tables`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/register-restaurant`; params?: Router.UnknownInputParams; };
    }
  }
}
